version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: America/Bogota
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  rebase-strategy: disabled
